### PR TITLE
Handle clicks on the calendar hosted in Shadow DOM

### LINKED ISSUE #101: Calendar closes on first click when used in Shadow DOM
I am hosting my React components in a Shadow DOM. This may be a bit esoteric right now, but it might be used more frequently in the future. Unfortunately, react-daterange-picker does not function in a Shadow DOM, because it closes the popup calendar whenever the first date is clicked. This happens because `onOutsideAction` does not detect that the click happened on the popup. `event.target` points to the DOM node that functions as the shadow root, so the test `this.wrapper.contains(event.target)` always fails.

There may be a way around this by using `Event.composedPath()`. I'll try putting together a PR later.

### PR DESCRIPTION
**Pull request by jorrit**
Fixes #101. I tried creating a test for this, but I can't seem to trigger a click on one of the buttons and make it bubble up to the document level using Jest.

### CODE REVIEW

**Comment by jorrit** [comment]
I am now using my branch via this NPM compatible branch: https://github.com/jorrit/react-daterange-picker-1/tree/shadowdomclicknpm

My change works fine for my use case.

**Comment by wojtekmaj** [comment]
Neat, thanks!

**Comment by wojtekmaj** [comment]
BTW if you can think of a test we could add for this, It'd be much appreciated.

**Comment by jorrit** [comment]
I tried, but generating events that bubble properly seems hard in jest / jsdom. I noticed that some click inside/outside cases had no tests either, so I figured that you also had found no way to build a test

**Comment by wojtekmaj** [comment]
Oh. I see! Well, let's test on production like real men. :joy:

**Pull request merged**
