### PR TITLE
Added format into the props in renderInputs.

### PR DESCRIPTION
**Pull request by tompiler**
Hi - I've added in the format prop to the renderInputs function as this allowed me to format the date with e.g. dd-M-y (the english way :D).

### CODE REVIEW

**Comment by wojtekmaj** [comment]
Hi,
this has already been added and you're just duplicating these values :)

**Comment by tompiler** [comment]
This actually still isn't working for me. I'm not sure why but I have to edit the function inside build for my app to work correctly - is there any way to see this a bit deeper than the tests?

**Comment by wojtekmaj** [comment]
Can you provide a reproduction of the bug you're seeing on CodeSandbox?

**Comment by tompiler** [comment]
Certainly will try - might take me a few days but bear with me :)

**Pull request closed without merging**
